services:
  dashboard:
    build: .
    container_name: typescore-dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python app/main.py
    networks:
      - typescore-network

networks:
  typescore-network:
    driver: bridge
