version: "3.8"

services:
  typescore-predictor:
    build: .
    container_name: typescore-predictor
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py
